### ISSUE TITLE
 Error executing the solver

### ISSUE THREAD

**Issue by andres190** [VROOM-Project/vroom-frontend#29]
Hi

 

I am trying to implement the VROOM project in ubuntu but when I run it I get the following error

 

I'll be doing something wrong, you can help me.

 

I greatly appreciate any comments

![novedad_vroom](https://user-images.githubusercontent.com/20262477/39659225-7f5da2a8-4fe9-11e8-890b-dee1a01fbe07.jpg)

**Comment by jcoupey** [comment]
This happens because the `vroom` command is not known system-wide so the system can't guess in which folder the executable is to be found. To confirm, just type `vroom` in a terminal and you'll probably get the same error. You have to ways to solve this:

1. assuming you're using `vroom-express` to handle the frontend requests, you can adjust the lookup  path for the executable by changing [this line](https://github.com/VROOM-Project/vroom-express/blob/master/src/index.js#L22) (just put the path to the `bin` folder created by the compilation process).

2. you can make the command accessible system-wide by adding its path to the PATH environment variable in your `~/.bashrc` file, like [explained here](https://stackoverflow.com/questions/7360889/adding-a-directory-to-path-in-ubuntu).

Using 1. is just configuration so will only work with `vroom-express`, whereas using 2. will also make `vroom` available for any command-line call.

**Comment by andres190** [comment]
Hi Julien

I appreciate your help, I have done what you told me, but I still have the
same problem.

It will be that I am doing something else wrong.


EXECUTION PROCESS

1. EXECUTE OSRM
2. EXECUTION VROOM-EXPRESS
3. EXECUTION VROOM FRONT-END

Is the way I run the files correct?

Thanks for your help.

1.

2

2018-05-06 8:34 GMT-05:00 Julien Coupey <notifications@github.com>:

**Comment by jcoupey** [comment]
The steps you describe are OK. Did you also [compile](https://github.com/VROOM-Project/vroom/wiki/Building) vroom? If so can you simply run `vroom -h` in a terminal and paste the output?

**Comment by andres190** [comment]
This is the result when I run the solver on VROOM EXPRESS





2018-05-07 1:56 GMT-05:00 Julien Coupey <notifications@github.com>:

**Comment by jcoupey** [comment]
`vroom-express` is just a wrapper for the http requests, you need to check that the solving engine (`vroom` command-line) itself is working. Please open a terminal and type:

```bash
vroom -h
```
then paste the output here.

**Comment by andres190** [comment]
When I run the vroom -h command, this appears.




2018-05-07 11:33 GMT-05:00 Julien Coupey <notifications@github.com>:

**Comment by jcoupey** [comment]
@andres190 I didn't get the results mentioned in you two previous posts: it seems like you intended to attach screenshots but for some reason nothing is showing up on the issue thread.

**Comment by andres190** [comment]
Hi Julien

I have uploaded the screenshots to the last 2 threads

2018-05-08 3:02 GMT-05:00 Julien Coupey <notifications@github.com>:

**Comment by jcoupey** [comment]
Thanks for the update. So you have the `vroom` executable compiled and working, but what probably happens is that you can't call it outside of the local `~/vroom/bin` folder (the system doesn't know where to find it).

You can configure the folder where to look for the executable at the `vroom-express` level. In your local copy of the `src/index.js` file, change [this line](https://github.com/VROOM-Project/vroom-express/blob/master/src/index.js#L22) by replacing 

```
path: '',
```

with the actual path on your system:

```
path: '~/vroom/bin/',
```

**Comment by andres190** [comment]
Hello Julien

Add the path where the bin folder of the vroom is located, but when I run the program I still get the error.

![novedad5_vroom](https://user-images.githubusercontent.com/20262477/39776006-28445ea6-52c5-11e8-8ff9-581d08ec4f8f.jpg)
![novedad6_vroom](https://user-images.githubusercontent.com/20262477/39776007-2865e440-52c5-11e8-8dd9-607a67e2d51c.jpg)

**Comment by andres190** [comment]
Hello Julien

Add the path where the bin folder of the vroom is located, but when I run
the program I still get the error.







2018-05-08 8:26 GMT-05:00 Julien Coupey <notifications@github.com>:

**Comment by jcoupey** [comment]
The last "/" is missing in `/home/desarrollo1/vroom/bin/`.

**Comment by andres190** [comment]
Hello Julien

Your help has helped me a lot, I really appreciate the time it took to help with this problem.

I finally managed to execute it locally!

THANK YOU

I wish you many successes.


![image](https://user-images.githubusercontent.com/20262477/39786923-5d9b5690-52e8-11e8-8186-52eef7b8f145.png)

**Comment by jcoupey** [comment]
Glad this finally works for you.
