### ISSUE TITLE
Tiles not rendering

### ISSUE THREAD

**Issue by amosfolz** [VROOM-Project/vroom-frontend#40]
When I try to change `var initCenter = L.latLng(48.8579,2.3494);` to coordinates in another country the map tiles will no longer load.

**Comment by amosfolz** [comment]
I did noticed the requests to tile.osm.org. 
![image](https://user-images.githubusercontent.com/33728190/48578844-c467e500-e8e8-11e8-8018-d6a3a254b23a.png)

However, just blank tiles appear. 
I guess I am a bit confused as I thought OSRM-backend handled the rendering of the map tiles?

**Comment by jcoupey** [comment]
No, the map tiles are totally unrelated to OSRM, they're from the OpenStreetMap servers. Note that the [tile usage policy](https://operations.osmfoundation.org/policies/tiles/) imposes some restrictions. If you badly need guarantees on tiles availability, you might consider using another third-party provider.

On the technical side, I don't get what's wrong. Do you have any error in the javascript console? Can you share the exact location you're using for `initCenter`? Did you make some other changes in the code?

**Comment by amosfolz** [comment]
There are no errors in the console. I probably just have something setup wrong. Here's what I did so far:
1. Changed that one line of code to: `var initCenter = L.latLng(-85.67227,40.506386);`
2. Ran `npm run dist`
3. Included `<div id="map"></div>`, `bundle.js` and the css files referenced in `index.html` to my custom page.

If I wanted to use another tile provider (such as mapbox), would it be as easy as making changes to `src/api.js` or would other changes need to be made as well? MapBox requires an accessToken to use their service.

**Comment by jcoupey** [comment]
My guess is that your coordinates are reversed as Leaflet uses `lat, lon` ordering. Using `var initCenter = L.latLng(40.506386, -85.67227);` instead works fine and lands somewhere around Chicago.

> would it be as easy as making changes to `src/api.js`

Yes, you'd have to adjust the `tileLayer` variable using [this kind of adress](https://stackoverflow.com/a/37167777).

**Comment by amosfolz** [comment]
> My guess is that your coordinates are reversed as Leaflet uses lat, lon ordering. Using var initCenter = L.latLng(40.506386, -85.67227); instead works fine and lands somewhere around Chicago.

You were correct about my coordinates being reversed and thank you for the helpful link! I was able to get it connected to mapbox with the instructions you provided.

**Comment by jcoupey** [comment]
Glad that worked out for you!
