### ISSUE TITLE
Add vehicles in addition to locations via one address per line

### ISSUE THREAD

**Issue by amosfolz** [VROOM-Project/vroom-frontend#41]
When uploading locations from a file with one location on each line, is it possible to also add vehicles from that same file?

**Comment by jcoupey** [comment]
No, uploading a list of addresses is the same as clicking on each of the geocoded points. The result is that the first geocoded point is used to define a vehicle and all subsequent points are seen as jobs.

If you want to define multiple vehicles from a file, the only way currently is to use a json file to describe the problem.

**Comment by amosfolz** [comment]
Thanks for the clarification.
