### ISSUE TITLE
Turn-by-turn instructions

### ISSUE THREAD

**Issue by amosfolz** [VROOM-Project/vroom-frontend#42]
Is there an easy way to get turn-by-turn instructions after a problem is solved? If that is outside the scope of vroom, would appreciate any thoughts you have on how to handle this.

**Comment by jcoupey** [comment]
Yes, I'd say this is out of scope for the core optimization engine, but I understand you might want that client-side. There are basically two options:

1. use the `route` requests to OSRM that VROOM performs after solving (to retrieve distance and geometry) and add what you need in the VROOM response
2. re-launch an OSRM `route` request on the client-side for each route

Option 2. could be as easy and straightforward as using [Leaflet Routing Machine](http://www.liedman.net/leaflet-routing-machine/). Option 1. means adjusting the C++ code to expand the response and then treating it manually with [osrm-text-instructions](https://github.com/Project-OSRM/osrm-text-instructions). Depending on your preferences, let me know if you need more pointers.

**Comment by amosfolz** [comment]
Thanks Julien. I am new to coding and therefore not sure I want to try learning C++ until I get a better grasp on the basics. I am going to look into #2 and will let you know if I run into any difficulties.

**Comment by jcoupey** [comment]
Good luck! Feel free to reopen if you have a follow-up question.

**Comment by jcoupey** [comment]
Since your coordinates are returned as strings, you'd have to parse them to feed them as [lat, lon] pairs to LRM. Or maybe have your API return arrays in the first place?

**Comment by amosfolz** [comment]
Thanks for the tip, that got me headed in the right direction and I was able to iterate through and get it in the format I needed.
