### ISSUE TITLE
Change path opacity onclick

### ISSUE THREAD

**Issue by AMohn9** [VROOM-Project/vroom-frontend#45]
When there are many paths in the same general area, the map starts to get cluttered and hard to read. It would be awesome if clicking on a path increased its opacity while decreasing the opacity of all others.

**Comment by jcoupey** [comment]
We currently have [a way to zoom](https://github.com/VROOM-Project/vroom-frontend/blob/7814c0737a5379d2d47e3b44296110ba52117197/src/utils/data_handler.js#L696-L706) to a specific route by clicking on the vehicle header in the right panel. Maybe it would make sense to add the opacity trick to the same action, and also bind it to a click on the route geometry.

@AMohn9 a PR for this would be welcome!

**Comment by jcoupey** [comment]
Fixed in #46.
