### ISSUE TITLE
front-end does not work on windows 

### ISSUE THREAD

**Issue by yongshenglian** [VROOM-Project/vroom-frontend#51]
Following the instruction we installed vroom-frontend on a PC running windows 10 through a powershell.  After the command "npm run serve" we have this error.  The npm works well on a linux server though.

beefy (v2.1.8) is listening on http://127.0.0.1:9966
200   91ms       592B  /
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn ./node_modules/.bin/browserify ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ./node_modules/.bin/browserify',
  path: './node_modules/.bin/browserify',
  spawnargs: [
    'C:\\project\\vroom-frontend-master\\vroom-frontend-master\\src\\map.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vroom-frontend@0.3.0 serve: `beefy src/map.js --browserify ./node_modules/.bin/browserify --live`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vroom-frontend@0.3.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yongs\AppData\Roaming\npm-cache\_logs\2020-05-21T13_43_51_206Z-debug.log

**Comment by jcoupey** [comment]
@yongshenglian where you able to run `npm install` without any problem?

The `serve` script rely on `browserify` being accessible under `./node_modules/.bin/browserify`. This error looks like the file/folder does not exist, could you check that?

**Comment by yongshenglian** [comment]
Julien,

  npm install has no problem. Browsrify is also in the right directory as
see from the screenshot. the file size is 1k only.

Yongsheng

[image: image.png]


[image: image.png]

**Comment by jcoupey** [comment]
Let's try to narrow things down, do you have a similar error when running `npm run build`?

**Comment by yongshenglian** [comment]
npm run build does show an error. It appears  "browserify -d src/map.js -o
bundle.raw.js && ./node_modules/.bin/uglifyjs bundle.raw.js -c -m -o
bundle.js" is not working right. So I run  "   ./node_modules/.bin/uglifyjs
bundle.raw.js -c -m -o bundle.js" separately to generate the bundle.js and
then remove it from the jason file. After that I can run "npm run build".

npm run serve works well as below. But when I opened the localhost it will
show an error message. I copied the error messages from both commands
below.






================================npm run build===========================
npm run build

> vroom-frontend@0.3.0 build
C:\project\vroom-frontend-master\vroom-frontend-master
> browserify -d src/map.js -o bundle.raw.js && ./node_modules/.bin/uglifyjs
bundle.raw.js -c -m -o bundle.js

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vroom-frontend@0.3.0 build: `browserify -d src/map.js -o
bundle.raw.js && ./node_modules/.bin/uglifyjs bundle.raw.js -c -m -o
bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vroom-frontend@0.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!
C:\Users\yongs\AppData\Roaming\npm-cache\_logs\2020-05-22T10_19_09_592Z-debug.log
PS C:\project\vroom-frontend-master\vroom-frontend-master>
./node_modules/.bin/uglifyjs bundle.raw.js -c -m -o bundle.js
WARN: Side effects in initialization of unused variable collapseControl
[bundle.raw.js:16671,4]



==========================npm run serve ======================

npm run serve

> vroom-frontend@0.3.0 serve
C:\project\vroom-frontend-master\vroom-frontend-master
> beefy src/map.js --browserify ./node_modules/.bin/browserify --live

beefy (v2.1.8) is listening on http://127.0.0.1:9966
200   34ms       592B  /
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn ./node_modules/.bin/browserify ENOENT
    at Process.ChildProcess._handle.onexit
(internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit
(internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ./node_modules/.bin/browserify',
  path: './node_modules/.bin/browserify',
  spawnargs: [
    'C:\\project\\vroom-frontend-master\\vroom-frontend-master\\src\\map.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vroom-frontend@0.3.0 serve: `beefy src/map.js --browserify
./node_modules/.bin/browserify --live`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vroom-frontend@0.3.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!
C:\Users\yongs\AppData\Roaming\npm-cache\_logs\2020-05-22T10_26_56_765Z-debug.log


====================================

**Comment by jcoupey** [comment]
Just a wild guess: could this be related to Windows using `\` for paths, or not understanding `./` to point to current folder? Maybe try changing this in the `package.json` commands...

Anyway, if you managed to run `npm run build`, you should be able to run `npm run dist` which calls the `scripts/dist.sh` script to generate a standalone version of the frontend in the `dist` folder.

Then you can serve this any way you like, the `beefy` thing is actually only useful for live reloads when changing the source files.

**Comment by yongshenglian** [comment]
Julien,

  Something is not right. We will just run on the linux server from now.

**Comment by jcoupey** [comment]
OK, closing here if you found a workaround. Feel free to reopen and submit the `npm run dist` error if needed.
