### ISSUE TITLE
Option to change leaflet geocoder

### ISSUE THREAD

**Issue by skarlsen** [VROOM-Project/vroom-frontend#52]
Hi!

A feature I think would enhance this project is the ability to change the leaflet default geocoder, in order to avoid getting soft and/or hard banned from Nominatim. This could be handled by hosting your own Nominatim-server and pointing leaflet to that instead of the default one. 

The defaults works wonderfully with a hosted vroom and osrm server (which I've pointed the frontend to in /src/config/api.js) when using the point-and-click interface, but I've run into soft bans when trying to add locations by using files with one coordinate per line. The routes I'm trying to optimize are a little under 1000 stops, so it's understandable that a soft ban is triggered when all those requests are sent in short order when uploading a file. 

Perhaps a workaround is using json-formatted files? Is the geocoder called then?

**Comment by jcoupey** [comment]
The purpose of this repo is to provide a simple demo interface. Of course if you end up using it intensively you should point various external requests to your own instances of the services: tiles, geocoding, overpass etc.

If you want to adjust the geocoding part, this is easily done [here](https://github.com/VROOM-Project/vroom-frontend/blob/master/src/utils/geocoder.js) as you would for any Leaflet-based map.

If you input json-formatted files, the `location` key will be used for coordinates and no geocoding request will be performed.

**Comment by jcoupey** [comment]
Closing as answered.
