### ISSUE TITLE
All capacity/amounts constraints have been removed.

### ISSUE THREAD

**Issue by luzzi8** [VROOM-Project/vroom-frontend#63]
Hello,

upon uploading a Vroom json request the following message is displayed:

> All capacity/amounts constraints have been removed.

Conceptually asked, why are these constraints removed?
I am also asking because I could not find anything about it in the documentation.

Some background information:

The front end version in use is:
https://github.com/iedmrc/vroom-frontend-docker 

In the commit history the error message last appeared here 24 oct 2018:
https://github.com/VROOM-Project/vroom-frontend/commit/959ddeadc2ce2f1920df656a67648bd2d217eaaf

This seems to imply the deployed frontend code is not up to date, is it?

Also saw this code:

```
    if (getVehiclesSize() + getJobsSize() > 1) {
      _deleteAmounts();
    }
```

Does this imply amount/capacity constraints are simply not supported by the front end?
How come? After all the backend server (solver) should be able to handle it.

Thank you very much for the great work and effort!

**Comment by jcoupey** [comment]
> Does this imply amount/capacity constraints are simply not supported by the front end?

No, if you upload a json file with amounts they will be transferred to the backend. The restriction is that we have no way to set an amount for a new job upon clicking on the map. So in order to avoid inconsistent behavior (some jobs with amounts some without), we simply erase all amounts for existing jobs/vehicles in that case and warn users about it.

This should only happen if you load a problem with amounts and then try to add some more jobs manually.

**Comment by luzzi8** [comment]
Thank you for your reply and explanation. 

I tested on http://map.vroom-project.org/ with the request below and I can confirm your statement.

When I test with the frontend version pulled in via the vroom-frontend-docker image (see my inital post) the amounts/capacities are removed right upon upload without adding an additional job manually.

```
{
  "vehicles": [
    {
      "id": 1,
      "start": [
        2.35044,
        48.71764
      ],
      "end": [
        2.35044,
        48.71764
      ],
      "capacity": [
        4
      ],
      "skills": [
        1,
        14
      ],
      "time_window": [
        1600416000,
        1600430400
      ]
    },
    {
      "id": 2,
      "start": [
        2.35044,
        48.71764
      ],
      "end": [
        2.35044,
        48.71764
      ],
      "capacity": [
        4
      ],
      "skills": [
        2,
        14
      ],
      "time_window": [
        1600416000,
        1600430400
      ],
      "breaks": [
        {
          "id": 2,
          "service": 300,
          "time_windows": [
            [
              1600423200,
              1600425000
            ]
          ]
        }
      ]
    }
  ],
  "jobs": [
    {
      "id": 1,
      "service": 300,
      "delivery": [
        1
      ],
      "location": [
        1.98935,
        48.701
      ],
      "skills": [
        1
      ],
      "time_windows": [
        [
          1600419600,
          1600423200
        ]
      ]
    },
    {
      "id": 2,
      "service": 300,
      "pickup": [
        1
      ],
      "location": [
        2.03655,
        48.61128
      ],
      "skills": [
        1
      ]
    },
    {
      "id": 5,
      "service": 300,
      "delivery": [
        1
      ],
      "location": [
        2.28325,
        48.5958
      ],
      "skills": [
        14
      ]
    },
    {
      "id": 6,
      "service": 300,
      "delivery": [
        1
      ],
      "location": [
        2.89357,
        48.90736
      ],
      "skills": [
        14
      ]
    }
  ],
  "shipments": []
}
```
