### ISSUE TITLE
Front end not displaying routes

### ISSUE THREAD

**Issue by stewgloves** [VROOM-Project/vroom-frontend#64]
Hello, from my understanding you should be able to import a json file with your output and it will be plotted on the vroom frontend. 

When I import my json it can detect my vehicles but no jobs:

![image](https://user-images.githubusercontent.com/93777743/186469957-e991bd9a-1ad0-4254-b730-16be0e42bed0.png)

Any idea? The JSON contains 50 jobs.

**Comment by jcoupey** [comment]
Hard to help you without more info. Can you share the file you're using? Are you seeing any errors in the console log?

**Comment by jcoupey** [comment]
Closing as stale.
